export const CATEGORIES = {
  SUCCESS: {
    id: "SUCCESS",
    label: "Settled / Exact Match",
    shortLabel: "Settled",
    color: "#175C3B",
    bg: "#EAF5EE",
    border: "#B4DEC4",
    description: "Transaction matched across Gateway, Bank statement, and Internal Ledger. Payout confirmed.",
    severity: "low",
  },
  BANK_DELAY: {
    id: "BANK_DELAY",
    label: "Bank Settlement Delay",
    shortLabel: "Delayed",
    color: "#8D4E03",
    bg: "#FEF7E6",
    border: "#F6DE98",
    description: "Payment captured successfully at Gateway, but credit is pending in the nodal bank processing queue.",
    severity: "medium",
  },
  DUPLICATE_UTR: {
    id: "DUPLICATE_UTR",
    label: "Duplicate Settlement Reference (UTR)",
    shortLabel: "Duplicate UTR",
    color: "#5B21B6",
    bg: "#F5F1FD",
    border: "#DDD6FE",
    description: "Multiple gateway records share the identical bank UTR reference, risking double credit or batch collision.",
    severity: "high",
  },
  AMOUNT_MISMATCH: {
    id: "AMOUNT_MISMATCH",
    label: "Settlement Amount Mismatch",
    shortLabel: "Amount Mismatch",
    color: "#991B1B",
    bg: "#FEF1F1",
    border: "#F8BDBD",
    description: "Gateway net payout differs from bank credited amount (fee miscalculation or unexpected deductions).",
    severity: "high",
  },
  MISSING_BANK_RECORD: {
    id: "MISSING_BANK_RECORD",
    label: "Missing Bank Record",
    shortLabel: "Missing Bank",
    color: "#9A3412",
    bg: "#FFF2EB",
    border: "#FDCBAE",
    description: "Gateway logged success, but no corresponding entry exists in bank statement files.",
    severity: "critical",
  },
  PARTIAL_SETTLEMENT: {
    id: "PARTIAL_SETTLEMENT",
    label: "Partial Settlement",
    shortLabel: "Partial",
    color: "#1E40AF",
    bg: "#EFF6FF",
    border: "#BFDBFE",
    description: "Internal ledger flagged a fractional payout. Remaining balance scheduled for future reconciliation.",
    severity: "medium",
  },
  UNCLASSIFIED: {
    id: "UNCLASSIFIED",
    label: "Unclassified Anomaly",
    shortLabel: "Unclassified",
    color: "#334155",
    bg: "#F1F5F9",
    border: "#CBD5E1",
    description: "Manual investigation required. Engine observed irregular trace patterns or missing metadata.",
    severity: "medium",
  },
};

export function getCategoryMeta(categoryId) {
  return CATEGORIES[categoryId] || {
    id: categoryId || "UNKNOWN",
    label: categoryId || "Unknown Anomaly",
    shortLabel: categoryId || "Unknown",
    color: "#334155",
    bg: "#F1F5F9",
    border: "#CBD5E1",
    description: "No specific diagnostic rule triggered.",
    severity: "medium",
  };
}
